version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=sparkreview
      - DATABASE_CLIENT=sqlite
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./database:/usr/src/database
      - ./src:/usr/src/app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always

