apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Spark {{ .Values.environment.name }} Sparkreview
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.environment.prefix }}.{{ .Values.domain }}
    cloud.google.com/load-balancer-type: Internal
  labels:
    k8s-app: {{ .Values.environment.prefix }}-sparkreview-{{ .Values.environment.name }}
  name: {{ .Values.environment.prefix }}-sparkreview-{{ .Values.environment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: tcp-80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: {{ .Values.environment.prefix }}-sparkreview-{{ .Values.environment.name }}
  sessionAffinity: None
  type: LoadBalancer
